"""initial schema

Revision ID: 5303b752c2e1
Revises: 
Create Date: 2026-04-26 12:57:27.957778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5303b752c2e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('bar_association_number', sa.String(length=120), nullable=True),
    sa.Column('primary_courts', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('official_phone', sa.String(length=40), nullable=True),
    sa.Column('fax', sa.String(length=40), nullable=True),
    sa.Column('official_email', sa.String(length=255), nullable=True),
    sa.Column('subscription_plan', sa.Enum('starter', 'professional', 'enterprise', name='subscription_plan_enum', native_enum=False), nullable=False),
    sa.Column('subscription_status', sa.Enum('trial', 'active', 'suspended', 'cancelled', name='subscription_status_enum', native_enum=False), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_association_number')
    )
    op.create_table('legal_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.Enum('fee_contract', 'poa_specific', 'receipt', 'defense_memo', 'client_letter', name='template_type_enum', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_templates_office_id'), ['office_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'partner', 'senior_lawyer', 'junior_lawyer', 'assistant', 'accountant', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=1024), nullable=True),
    sa.Column('notification_preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=False),
    sa.Column('quiet_hours_end', sa.Time(), nullable=False),
    sa.Column('daily_digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('fcm_token', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_office_id'), ['office_id'], unique=False)

    op.create_table('active_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('device_type', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_office_id'), ['office_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('client_number', sa.String(length=40), nullable=False),
    sa.Column('client_type', sa.Enum('individual', 'company', 'government', name='client_type_enum', native_enum=False), nullable=False),
    sa.Column('full_name_ar', sa.String(length=255), nullable=False),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('national_id_or_commercial_reg', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth_or_founding', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=120), nullable=True),
    sa.Column('profession_or_activity', sa.String(length=255), nullable=True),
    sa.Column('governorate', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('building_number', sa.String(length=50), nullable=True),
    sa.Column('primary_phone', sa.String(length=40), nullable=False),
    sa.Column('secondary_phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=40), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=40), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=120), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('assigned_lawyer_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id', 'client_number', name='uq_client_number_per_office')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_office_id'), ['office_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('client', 'case', 'session', name='document_entity_type_enum', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Enum('defense_memo', 'judgment', 'contract', 'poa', 'receipt', 'correspondence', 'session_minutes', 'other', name='global_document_type_enum', native_enum=False), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_office_id'), ['office_id'], unique=False)

    op.create_table('member_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'partner', 'senior_lawyer', 'junior_lawyer', 'assistant', 'accountant', name='invite_role_enum', native_enum=False), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('member_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_invites_office_id'), ['office_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_push', sa.Boolean(), nullable=False),
    sa.Column('sent_email', sa.Boolean(), nullable=False),
    sa.Column('sent_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_office_id'), ['office_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('case_year', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=False),
    sa.Column('court_circuit', sa.String(length=255), nullable=True),
    sa.Column('case_type', sa.Enum('criminal', 'civil', 'commercial', 'administrative', 'labor', 'family', 'constitutional', 'enforcement', name='case_type_enum', native_enum=False), nullable=False),
    sa.Column('case_subject', sa.Text(), nullable=True),
    sa.Column('defendant_name', sa.String(length=255), nullable=True),
    sa.Column('defendant_lawyer', sa.String(length=255), nullable=True),
    sa.Column('responsible_lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('assistant_lawyer_id', sa.Uuid(), nullable=True),
    sa.Column('client_role', sa.Enum('plaintiff', 'defendant', 'appellant', 'appellee', 'other', name='client_role_case_enum', native_enum=False), nullable=False),
    sa.Column('fee_type', sa.Enum('fixed', 'percentage', 'hourly', 'mixed', name='case_fee_type_enum', native_enum=False), nullable=False),
    sa.Column('agreed_fee_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retainer_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('new', 'active', 'awaiting_judgment', 'suspended', 'closed', name='case_status_enum', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('normal', 'important', 'critical', name='case_priority_enum', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['responsible_lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_office_id'), ['office_id'], unique=False)

    op.create_table('client_appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attendance_status', sa.Enum('pending', 'attended', 'absent', 'postponed', name='attendance_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_appointments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_appointments_office_id'), ['office_id'], unique=False)

    op.create_table('client_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Enum('national_id_front', 'national_id_back', 'passport', 'commercial_reg', 'tax_card', 'other', name='client_doc_type_enum', native_enum=False), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_documents_office_id'), ['office_id'], unique=False)

    op.create_table('case_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_notes_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_notes_office_id'), ['office_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('expense_type', sa.Enum('court_fees', 'transport', 'stamp', 'expert', 'other', name='expense_type_enum', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('receipt_url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_office_id'), ['office_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=120), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('line_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type_enum', native_enum=False), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', name='invoice_status_enum', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id', 'invoice_number', name='uq_invoice_number_per_office')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_office_id'), ['office_id'], unique=False)

    op.create_table('judgments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('judgment_date', sa.Date(), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('court_circuit', sa.String(length=255), nullable=True),
    sa.Column('judge_name', sa.String(length=255), nullable=True),
    sa.Column('judgment_type', sa.Enum('primary', 'appellate', 'cassation', 'constitutional', name='judgment_type_enum', native_enum=False), nullable=False),
    sa.Column('result', sa.Enum('full_win', 'partial_win', 'loss', 'postponed', 'formal', name='judgment_result_enum', native_enum=False), nullable=False),
    sa.Column('judgment_text', sa.Text(), nullable=True),
    sa.Column('judgment_file_url', sa.String(length=1024), nullable=True),
    sa.Column('awarded_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('appeal_tracked', sa.Boolean(), nullable=False),
    sa.Column('appeal_type', sa.Enum('appeal', 'cassation', name='appeal_type_enum', native_enum=False), nullable=True),
    sa.Column('appeal_deadline', sa.Date(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judgments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgments_office_id'), ['office_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'check', 'vodafone_cash', 'card', name='payment_method_enum', native_enum=False), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('receipt_file_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_office_id'), ['office_id'], unique=False)

    op.create_table('powers_of_attorney',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('poa_type', sa.Enum('general', 'specific', 'judicial', 'banking', 'real_estate', 'commercial', name='poa_type_enum', native_enum=False), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notary_office', sa.String(length=255), nullable=True),
    sa.Column('notary_number', sa.String(length=120), nullable=True),
    sa.Column('linked_case_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expiring_soon', 'expired', name='poa_status_enum', native_enum=False), nullable=False),
    sa.Column('responsible_lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['linked_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['responsible_lawyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('powers_of_attorney', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_powers_of_attorney_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_powers_of_attorney_office_id'), ['office_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_time', sa.Time(), nullable=True),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('court_circuit', sa.String(length=255), nullable=True),
    sa.Column('session_type', sa.Enum('first', 'proof', 'pleading', 'judgment', 'emergency', 'postponement', name='session_type_enum', native_enum=False), nullable=False),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('postponed', 'judgment', 'decision', 'proof', 'attended_absent', name='session_result_enum', native_enum=False), nullable=True),
    sa.Column('result_notes', sa.Text(), nullable=True),
    sa.Column('next_session_date', sa.Date(), nullable=True),
    sa.Column('minutes_file_url', sa.String(length=1024), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_office_id'), ['office_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Enum('urgent', 'important', 'normal', name='task_priority_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'done', name='task_status_enum', native_enum=False), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('daily', 'weekly', 'monthly', name='task_recurrence_enum', native_enum=False), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_office_id'), ['office_id'], unique=False)

    op.create_table('appeal_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('judgment_id', sa.Uuid(), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appeal_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appeal_reminders_judgment_id'), ['judgment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appeal_reminders_office_id'), ['office_id'], unique=False)

    op.create_table('enforcement_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('judgment_id', sa.Uuid(), nullable=True),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('official_enforcement_number', sa.String(length=120), nullable=False),
    sa.Column('enforcement_court', sa.String(length=255), nullable=False),
    sa.Column('enforcement_officer', sa.String(length=255), nullable=True),
    sa.Column('enforcement_type', sa.Enum('real_estate_seizure', 'money_seizure', 'movables_seizure', 'eviction', 'delivery', name='enforcement_type_enum', native_enum=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('debtor_name', sa.String(length=255), nullable=False),
    sa.Column('debtor_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'suspended', name='enforcement_status_enum', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enforcement_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enforcement_files_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enforcement_files_judgment_id'), ['judgment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enforcement_files_office_id'), ['office_id'], unique=False)

    op.create_table('enforcement_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enforcement_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collected_at', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enforcement_id'], ['enforcement_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enforcement_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enforcement_payments_enforcement_id'), ['enforcement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enforcement_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enforcement_payments_enforcement_id'))

    op.drop_table('enforcement_payments')
    with op.batch_alter_table('enforcement_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enforcement_files_office_id'))
        batch_op.drop_index(batch_op.f('ix_enforcement_files_judgment_id'))
        batch_op.drop_index(batch_op.f('ix_enforcement_files_case_id'))

    op.drop_table('enforcement_files')
    with op.batch_alter_table('appeal_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeal_reminders_office_id'))
        batch_op.drop_index(batch_op.f('ix_appeal_reminders_judgment_id'))

    op.drop_table('appeal_reminders')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_office_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_case_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_office_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_case_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('powers_of_attorney', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powers_of_attorney_office_id'))
        batch_op.drop_index(batch_op.f('ix_powers_of_attorney_client_id'))

    op.drop_table('powers_of_attorney')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_office_id'))
        batch_op.drop_index(batch_op.f('ix_payments_client_id'))
        batch_op.drop_index(batch_op.f('ix_payments_case_id'))

    op.drop_table('payments')
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judgments_office_id'))
        batch_op.drop_index(batch_op.f('ix_judgments_case_id'))

    op.drop_table('judgments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_office_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_case_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_office_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_client_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_case_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_notes_office_id'))
        batch_op.drop_index(batch_op.f('ix_case_notes_case_id'))

    op.drop_table('case_notes')
    with op.batch_alter_table('client_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_documents_office_id'))
        batch_op.drop_index(batch_op.f('ix_client_documents_client_id'))

    op.drop_table('client_documents')
    with op.batch_alter_table('client_appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_appointments_office_id'))
        batch_op.drop_index(batch_op.f('ix_client_appointments_client_id'))

    op.drop_table('client_appointments')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_office_id'))
        batch_op.drop_index(batch_op.f('ix_cases_client_id'))

    op.drop_table('cases')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_office_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('member_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_invites_office_id'))
        batch_op.drop_index(batch_op.f('ix_member_invites_email'))

    op.drop_table('member_invites')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_office_id'))
        batch_op.drop_index(batch_op.f('ix_documents_entity_id'))

    op.drop_table('documents')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_office_id'))

    op.drop_table('clients')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_office_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_user_id'))

    op.drop_table('active_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_office_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('legal_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_templates_office_id'))

    op.drop_table('legal_templates')
    op.drop_table('offices')
    # ### end Alembic commands ###
